server:
  port: 10000
spring:
  zipkin:
    base-url: http://localhost:9411/ #地址
    discovery-client-enabled: false  #让nacos把他url，而不要当作服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比 0.1--1.0
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: 898989898989
          uri: lb://shop-product
          order: 1
          predicates:
            - Path=/product-sxy/**
          filters:
            - StripPrefix=1
        - id: sssssssssssssssss
          uri: lb://shop-order
          order: 1
          predicates:
            - Path=/order-sxy/**
          filters:
            - StripPrefix=1
        - id: shop-user
          uri: lb://shop-user
          order: 1
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


