#\u7AEF\u53E3
server:
  port: 9071

#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  #nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: shop-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root#123
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis Plus\u914D\u7F6E
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#\u6253\u5370\u65E5\u5FD7
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876

