#server:
#  port: 9999
#
#spring:
#  application:
#    name: shop-common
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root#123
#    type: com.alibaba.druid.pool.DruidDataSource
