#\u7AEF\u53E3
server:
  port: 9091
#设置tomcat 最大线程数
  tomcat:
    max-threads: 5
#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  zipkin:
    base-url: http://localhost:9411/ #地址
    discovery-client-enabled: false  #让nacos把他url，而不要当作服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比 0.1--1.0

  application:
    name: shop-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root#123
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080  #监控台
        port: 2222  #跟控制台交流的端口
#开启Feign对Sentinel的支持
#mybatis Plus\u914D\u7F6E
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #\u6253\u5370\u65E5\u5FD7
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印mybatis plus 日志
#feign: 整合feign失败！
#  sentinel:
#    enabled: true
rocketmq:
  name-server: 127.0.0.1:9876 #rocketMQ服务的地址
  producer:
    group: shop-order # 生产者组
